name: weather
description: Check the weather wherever you want!

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_svg: ^1.1.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.1.1
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/